### ISSUE TITLE
Error making volume mountpoint for volume /var/run/docker.sock when running with podman

### ISSUE THREAD

**Issue by fnordian** [testcontainers/testcontainers-node#203]
When trying to run a jest testcase that uses testcontainers' KafkaContainer, the container won't start. Instead an error is produced:

`[Error: (HTTP code 500) server error - make cli opts(): error making volume mountpoint for volume /var/run/docker.sock: mkdir /var/run/docker.sock: permission denied ]`

I am using podman on Fedora 34. Testcontainers under java are working fine.

Here's my test-case:
```typescript
import {Kafka} from "kafkajs";
import {KafkaContainer} from "testcontainers";

jest.setTimeout(30000);

const producerPromise = new KafkaContainer()
    .withExposedPorts(9093)
    .start()
    .then(container => {
        const client = new Kafka({
            brokers: [`${container.getHost()}:${container.getMappedPort(9093)}`],
        });
        const producer = client.producer();
        return producer.connect().then(value => producer);
    })
    ;

describe('Publishing data', () => {

    it('should publish data', () => {
        return expect(producerPromise.then(producer => {
            producer.send({
                messages: [{
                    value: "foo-data"
                }], topic: "bar-topic"

            })
        })).resolves.toBeTruthy();

    });
});
```

I set `DOCKER_HOST` to `unix:///var/run/user/1000/podman/podman.sock`

**Comment by cristianrgreco** [comment]
Hi @fnordian, thanks for sharing. Could you please share the error with the stacktrace? I suspect the permission denied error is coming from trying to create the Reaper

**Comment by fnordian** [comment]
@cristianrgreco, I am not able to get a stack-trace out of a jest test. But when I set `TESTCONTAINERS_RYUK_DISABLED=true`, the error goes away, kafka & zk containers are created, and `Error: socket hang up` is thrown.

**Comment by cristianrgreco** [comment]
I see in this issue you are setting `DOCKER_HOST`, but the Java version which you say works for you uses `TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE`:

> (https://github.com/testcontainers/testcontainers-java/blob/8965712f239ae3c449cec579264af5e79265f314/core/src/main/java/org/testcontainers/DockerClientFactory.java#L146-L147)

Are you also setting `TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE` in your Java example?

**Comment by fnordian** [comment]
Yes, it's set to the file-path of the unix-socket.

**Comment by cristianrgreco** [comment]
Thanks @fnordian, please update to testcontainers 7.9.0 and set `TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE` to your podman socket accordingly

**Comment by cristianrgreco** [comment]
Hi @fnordian, could you please confirm the issue is now resolved?

**Comment by abcfy2** [comment]
Hi @cristianrgreco . I try to set `TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE`, but still not working. Would you please help ?

```sh
$ export DOCKER_HOST="unix://$XDG_RUNTIME_DIR/podman/podman.sock"
$ export TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE="${DOCKER_HOST}"
$ export DEBUG='testcontainers*'
$ npm test
...

2022-11-18T08:30:52.352Z testcontainers INFO  Using Docker client strategy: ConfigurationStrategy, Docker host: localhost
2022-11-18T08:30:52.352Z testcontainers DEBUG Fetching system diagnostics
2022-11-18T08:30:52.354Z testcontainers DEBUG No registry auth locator found for registry: "https://index.docker.io/v1/"
2022-11-18T08:30:52.354Z testcontainers DEBUG Checking if image exists: postgres:13.3-alpine
2022-11-18T08:30:52.364Z testcontainers INFO  Pulling image: postgres:13.3-alpine
2022-11-18T08:30:52.481Z testcontainers INFO  Unable to detect docker-compose version, is it installed? Error: spawn docker-compose ENOENT
2022-11-18T08:30:52.481Z testcontainers DEBUG System diagnostics: {"node":{"version":"v18.12.1","architecture":"x64","platform":"linux"},"docker":{"serverVersion":"4.3.1","operatingSystem":"manjaro","operatingSystemType":"linux","architecture":"amd64","cpus":16,"memory":14498271232}}
2022-11-18T08:30:58.166Z testcontainers TRACE Pulling postgres:13.3-alpine - ed849f5f685e - Already exists
2022-11-18T08:30:58.167Z testcontainers TRACE Pulling postgres:13.3-alpine - c7f8a1ea71cb - Already exists
2022-11-18T08:30:58.167Z testcontainers TRACE Pulling postgres:13.3-alpine - 0d265a24fb71 - Already exists
2022-11-18T08:30:58.167Z testcontainers TRACE Pulling postgres:13.3-alpine - 64d8912b293d - Already exists
2022-11-18T08:30:58.167Z testcontainers TRACE Pulling postgres:13.3-alpine - 06559c1681e8 - Already exists
2022-11-18T08:30:58.167Z testcontainers TRACE Pulling postgres:13.3-alpine - 3a646df07e94 - Already exists
2022-11-18T08:30:58.167Z testcontainers TRACE Pulling postgres:13.3-alpine - 1e40d492b730 - Already exists
2022-11-18T08:30:58.167Z testcontainers TRACE Pulling postgres:13.3-alpine - 29291e31a76a - Already exists
2022-11-18T08:30:58.168Z testcontainers TRACE Pulling postgres:13.3-alpine - f0b3bc4eab99 - Pulling fs layer
2022-11-18T08:30:58.179Z testcontainers TRACE Pulling postgres:13.3-alpine - f0b3bc4eab99 - Download complete
2022-11-18T08:30:58.185Z testcontainers DEBUG Creating new Reaper for session: cfad0f45594c7aca6a9ece237668cf13
2022-11-18T08:30:58.186Z testcontainers DEBUG Re-using cached auth for registry https://index.docker.io/v1/
2022-11-18T08:30:58.186Z testcontainers DEBUG Checking if image exists: testcontainers/ryuk:0.3.2
2022-11-18T08:30:58.195Z testcontainers INFO  Pulling image: testcontainers/ryuk:0.3.2
2022-11-18T08:31:05.229Z testcontainers TRACE Pulling testcontainers/ryuk:0.3.2 - 3061e9946820 - Already exists
2022-11-18T08:31:05.230Z testcontainers TRACE Pulling testcontainers/ryuk:0.3.2 - 23d9b994594f - Already exists
2022-11-18T08:31:05.231Z testcontainers TRACE Pulling testcontainers/ryuk:0.3.2 - 31603596830f - Already exists
2022-11-18T08:31:05.231Z testcontainers TRACE Pulling testcontainers/ryuk:0.3.2 - b24c56207c68 - Pulling fs layer
2022-11-18T08:31:05.242Z testcontainers TRACE Pulling testcontainers/ryuk:0.3.2 - b24c56207c68 - Download complete
2022-11-18T08:31:05.247Z testcontainers INFO  Creating container for image: testcontainers/ryuk:0.3.2
2022-11-18T08:31:05.253Z testcontainers ERROR Failed to create container for image testcontainers/ryuk:0.3.2: Error: (HTTP code 500) server error - fill out specgen: unix:///run/user/1000/podman/podman.sock:/var/run/docker.sock:rw: incorrect volume format, should be [host-dir:]ctr-dir[:option] 
  ✖ _core › services › dbService › before hook Rejected promise returned by test
  ─

  _core › services › dbService › before hook

  Rejected promise returned by test. Reason:

  Error {
    json: {
      cause: 'incorrect volume format, should be [host-dir:]ctr-dir[:option]',
      message: 'fill out specgen: unix:///run/user/1000/podman/podman.sock:/var/run/docker.sock:rw: incorrect volume format, should be [host-dir:]ctr-dir[:option]',
      response: 500,
    },
    reason: 'server error',
    statusCode: 500,
    message: '(HTTP code 500) server error - fill out specgen: unix:///run/user/1000/podman/podman.sock:/var/run/docker.sock:rw: incorrect volume format, should be [host-dir:]ctr-dir[:option] ',
  }

  › node_modules/docker-modem/lib/modem.js:336:17
  › getCause (node_modules/docker-modem/lib/modem.js:366:7)
  › Modem.buildPayload (node_modules/docker-modem/lib/modem.js:335:5)
  › IncomingMessage.<anonymous> (node_modules/docker-modem/lib/modem.js:303:16)

  ─


```
